### ISSUE TITLE
Invert file order

### ISSUE THREAD

**Issue by PeterFour** [FooSoft/mangle#16]
Is there an easy way to swap the file order when a folder is loaded ?

**Comment by catmanjan** [comment]
Is this related to #11?

**Comment by PeterFour** [comment]
Hum not really the order is correct but inverted

**Comment by leoboiko** [comment]
I'm getting this too.  Files named like this:

    image01-001-1.jpg
    image01-001-2.jpg
    image01-002-1.jpg
    image01-002-2.jpg
    image02-001-1.jpg
    image02-001-2.jpg
    image02-002-1.jpg
    image02-002-2.jpg

(image${volume}-${image}-${pagehalf}) appear in mange in this order:

    image01-002-2.jpg
    image01-002-1.jpg
    image01-001-2.jpg
    image01-001-1.jpg
    image02-002-2.jpg
    image02-002-1.jpg
    image02-001-2.jpg
    image02-001-1.jpg

That is, the first number is correct and increasing, while the other two numbers are decreasing.

**Comment by naparuba** [comment]
I have a pull reuqest to propose about this, I use a custom function instead of the natsort lib that have this bug.

I clean my repo and I'll sent it :)

**Comment by naparuba** [comment]
cf https://github.com/FooSoft/mangle/pull/18 :)

**Comment by naparuba** [comment]
coe is ok, exe will be available soon ^^

**Comment by FooSoft** [comment]
Fixed, new release posted
