### ISSUE TITLE
Wishlist: Japanese page order

### ISSUE THREAD

**Issue by leoboiko** [FooSoft/mangle#17]
It's very cool that mangle has the "split page" option.  Unfortunately it doesn't work for Japanese-language manga.  The reason is that, if the scan is double-page, Western order will result like this:

    0.jpg: [1|2]
    1.jpg: [3|4]
    2.jpg: [5|6]

(where the brackets represent images and the numbers, pages.)  Japanese order, meanwhile, is like this:

    0.jpg: [2|1]
    1.jpg: [4|3]
    2.jpg: [6|5]

I.e. the right half of each image comes first.

Would it be possible to add a binary option to use Japanese page order?

Thanks for great software!

**Comment by leoboiko** [comment]
Incidentally, here's a workaround if anyone's dealing with the same problem (using bash and ImageMagick):

```bash
for i in *.jpg; do convert -crop 50%x100% +repage "$i" crop/"$i"; done
for i in crop/*-0.jpg; do mv "$i" "${i/-0.jpg/-2.jpg}"; done
```

Adapt as needed.

**Comment by naparuba** [comment]
I have a patch with this feature (it add another option, right=>left and left=>right in the book). I'll propose a pull request :)

**Comment by naparuba** [comment]
cf https://github.com/FooSoft/mangle/pull/18 :)

**Comment by naparuba** [comment]
master version is OK, exe will be available soon :)

**Comment by FooSoft** [comment]
Fixed, new release posted
