### ISSUE TITLE
New profile for Kindle Paperwhite 3.

### ISSUE THREAD

**Issue by Splike** [FooSoft/mangle#20]
Hi!

Please add a profile for the "Kindle Paperwhite 3". The resolution of this device is 1448 × 1072 (300ppi)

**Comment by catmanjan** [comment]
PR @21

**Comment by catmanjan** [comment]
See PR #21

**Comment by Splike** [comment]
Great, thanks!
I hope a new release is pushed soon.

**Comment by naparuba** [comment]
I'm working on the exe building ^^

**Comment by FooSoft** [comment]
Fixed, new release posted
