### ISSUE TITLE
I've ported the code to Python 3 and PyQt5 !

### ISSUE THREAD

**Issue by gigajosh** [FooSoft/mangle#30]
Hi, I've updated the code for Python 3 and PyQt5 locally. 
I've now successfully run the updated application with Python 3 from terminal on Mac and used it to generate a 50+ page comic with the "Images & CBZ & PDF" option for Kindle Paperwhite. I've played with the other options, like stretching and borders and they seem to work.
I've tested saving and re-opening a .mngl file, deleting added images works fine. 
Would you like to update this repo with these changes, i.e. shall I create Pull request for this, or would you prefer I fork your repo and do it there?
Congrats for the work on this!

**Comment by FooSoft** [comment]
Sounds cool, send a PR 👍🏻 
Mangle is definitely overdue for an update!

**Comment by axu2** [comment]
Hey, how do you run it locally? (Either the old or Python3 version.)

**Comment by axu2** [comment]
@gigajosh I got your code to run, but do you know the specific versions of python and pyinstaller I need to actually build a binary?

**Comment by gigajosh** [comment]
Hey @axu2, did you find your way? I was caught up with other stuff so missed your message. I’m going to close the issue however, as I can see development has started again and this issue doesn’t need to be open. If you’re still stuck with creating the binary, probably best to create a new issue.

**Comment by axu2** [comment]
Hi @gigajosh that Python3 port was just a copy paste of your branch. Do you know how to build a binary using your branch? The binary build is very important.
