### ISSUE TITLE
Prebuilt executable is old/has bugs (And I made a new one)

### ISSUE THREAD

**Issue by axu2** [FooSoft/mangle#35]
Please update the included prebuilt executable! PR #34 shows how to build it!

It's old and has bugs that have been already been fixed. (Like split page overwriting).

And include it using GitHub releases!

If you add me as a contributor I'll do it myself :)

Here's one I built myself:

https://github.com/axu2/mangle/releases

**Comment by axu2** [comment]
https://github.com/axu2/mangle/releases

Small feature add

**Comment by axu2** [comment]
@FooSoft Do you want to build a new executable? I have instructions in the readme. Or you can just take the exe I built. Been using it for many months now.

**Comment by FooSoft** [comment]
@axu2 thanks, I've updated the binaries on the site. I haven't used Windows for years, so thanks for figuring out how to get this packaged there again.
